### ISSUE TITLE
1.8 Restrict access by end-user

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#3]
### User Story
An information manager would like to  restrict access to datasets by end-users 

### Acceptance Criteria

- [x] An information can restrict access to a dataset by end-users

### Tasks

- [x] Install[ restricted extension](https://github.com/EnviDat/ckanext-restricted)

**Comment by ismail-shahzad** [comment]
Checked https://github.com/anuveyatsu/ckanext-restricted. It is not compatible with CKAN 2.9.7

<details>
<summary> Traceback </summary> 

  ```python
  Traceback (most recent call last):
    File "/usr/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
      rv = self.dispatch_request()
    File "/usr/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
      return self.view_functions[rule.endpoint](**req.view_args)
    File "/srv/app/src/ckan/ckan/config/middleware/../../views/dataset.py", line 501, in read
      return base.render(
    File "/srv/app/src/ckan/ckan/lib/base.py", line 151, in render
      return flask_render_template(template_name, **extra_vars)
    File "/usr/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
      return _render(
    File "/usr/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
      rv = template.render(context)
    File "/usr/lib/python3.9/site-packages/jinja2/asyncsupport.py", line 76, in render
      return original_render(self, *args, **kwargs)
    File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1008, in render
      return self.environment.handle_exception(exc_info, True)
    File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 780, in handle_exception
      reraise(exc_type, exc_value, tb)
    File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 37, in reraise
      raise value.with_traceback(tb)
    File "/srv/app/src/ckan/ckan/templates/package/read.html", line 1, in <module>
      {% extends "package/read_base.html" %}
    File "/srv/app/src/ckan/ckan/templates/package/read_base.html", line 1, in <module>
      {% extends "package/base.html" %}
    File "/srv/app/src/ckan/ckan/templates/package/base.html", line 4, in <module>
      {% set dataset_type = dataset_type or pkg.type or 'dataset' %}
    File "/srv/app/src/ckan/ckan/templates/page.html", line 1, in <module>
      {% extends "base.html" %}
    File "/srv/app/src/ckanext-restricted/ckanext/restricted/templates/base.html", line 1, in <module>
      {% ckan_extends %}
    File "/srv/app/src/ckan/ckan/templates/base.html", line 105, in <module>
      {%- block page %}{% endblock -%}
    File "/srv/app/src/ckan/ckan/templates/page.html", line 19, in <module>
      {%- block content %}
    File "/srv/app/src/ckan/ckan/templates/page.html", line 22, in <module>
      {% block main_content %}
    File "/srv/app/src/ckan/ckan/templates/page.html", line 74, in <module>
      {% block primary %}
    File "/srv/app/src/ckan/ckan/templates/page.html", line 87, in <module>
      {% block primary_content %}
    File "/srv/app/src/ckan/ckan/templates/page.html", line 107, in <module>
      {% block primary_content_inner %}
    File "/srv/app/src/ckan/ckan/templates/package/read.html", line 44, in <module>
      {% block package_resources %}
    File "/srv/app/src/ckan/ckan/templates/package/read.html", line 45, in <module>
      {% snippet "package/snippets/resources_list.html", pkg=pkg, resources=pkg.resources, is_activity_archive=is_activity_archive %}
    File "/srv/app/src/ckan/ckan/lib/jinja_extensions.py", line 274, in _call
      return base.render_snippet(*args, **kwargs)
    File "/srv/app/src/ckan/ckan/lib/base.py", line 95, in render_snippet
      output = render(template_name, extra_vars=kw)
    File "/srv/app/src/ckan/ckan/lib/base.py", line 151, in render
      return flask_render_template(template_name, **extra_vars)
    File "/usr/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
      return _render(
    File "/usr/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
      rv = template.render(context)
    File "/usr/lib/python3.9/site-packages/jinja2/asyncsupport.py", line 76, in render
      return original_render(self, *args, **kwargs)
    File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1008, in render
      return self.environment.handle_exception(exc_info, True)
    File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 780, in handle_exception
      reraise(exc_type, exc_value, tb)
    File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 37, in reraise
      raise value.with_traceback(tb)
    File "/srv/app/src/ckan/ckan/templates/package/snippets/resources_list.html", line 15, in <module>
      {% block resource_list %}
    File "/srv/app/src/ckan/ckan/templates/package/snippets/resources_list.html", line 18, in <module>
      {% block resource_list_inner %}
    File "/srv/app/src/ckan/ckan/templates/package/snippets/resources_list.html", line 21, in <module>
      {% snippet 'package/snippets/resource_item.html', pkg=pkg, res=resource, can_edit=can_edit, is_activity_archive=is_activity_archive %}
    File "/srv/app/src/ckan/ckan/lib/jinja_extensions.py", line 274, in _call
      return base.render_snippet(*args, **kwargs)
    File "/srv/app/src/ckan/ckan/lib/base.py", line 95, in render_snippet
      output = render(template_name, extra_vars=kw)
    File "/srv/app/src/ckan/ckan/lib/base.py", line 151, in render
      return flask_render_template(template_name, **extra_vars)
    File "/usr/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
      return _render(
    File "/usr/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
      rv = template.render(context)
    File "/usr/lib/python3.9/site-packages/jinja2/asyncsupport.py", line 76, in render
      return original_render(self, *args, **kwargs)
    File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1008, in render
      return self.environment.handle_exception(exc_info, True)
    File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 780, in handle_exception
      reraise(exc_type, exc_value, tb)
    File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 37, in reraise
      raise value.with_traceback(tb)
    File "/srv/app/src/ckanext-restricted/ckanext/restricted/templates/package/snippets/resource_item.html", line 5, in <module>
      {% set url = h.url_for(controller='package', action=url_action, id=pkg.name, resource_id=res.id) %}
    File "/srv/app/src/ckan/ckan/lib/helpers.py", line 353, in url_for
      my_url = _url_for_flask(*args, **kw)
    File "/srv/app/src/ckan/ckan/lib/helpers.py", line 415, in _url_for_flask
      my_url = _flask_default_url_for(*args, **kw)
    File "/usr/lib/python3.9/site-packages/flask/helpers.py", line 370, in url_for
      return appctx.app.handle_url_build_error(error, endpoint, values)
    File "/usr/lib/python3.9/site-packages/flask/app.py", line 2215, in handle_url_build_error
      reraise(exc_type, exc_value, tb)
    File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
      raise value
    File "/usr/lib/python3.9/site-packages/flask/helpers.py", line 357, in url_for
      rv = url_adapter.build(
    File "/usr/lib/python3.9/site-packages/werkzeug/routing.py", line 2179, in build
      raise BuildError(endpoint, values, method, self)
  werkzeug.routing.BuildError: Could not build url for endpoint 'package.resource_read' with values ['id', 'resource_id']. Did you mean 'dataset_resource.read' instead?

```
</details>

**Comment by juanbrits** [comment]
@MuhammadIsmailShahzad need to understand what the requirements will are to upgrade restricted to be compatible with CKAN 2.9.7.

Can you timebox an investigation of maybe 2 hours to see if we can accomplish this and what effort (time) you would estimate it to take?

**Comment by sagargg** [comment]
This is fixed here but needs to test. 
https://github.com/datopian/ckanext-restricted/commit/94c7edf0752dcb24fa6134005cf82838b3a63985
https://github.com/datopian/ckanext-ubdc/blob/master/ckanext/ubdc/dataset.yaml

**Comment by juanbrits** [comment]
@sagargg I can assist with testing but might need some help on how to do so?

**Comment by sagargg** [comment]
@juanbrits Sure, we have some deployment issues waiting to be fixed by SRE.

**Comment by juanbrits** [comment]
hi @sagargg have the issues been resolved?

**Comment by sagargg** [comment]
@juanbrits  this is deployed on staging env. Now publishers can add resource level restrictions. 
cc @MuhammadIsmailShahzad 
<img width="998" alt="Screenshot 2022-11-17 at 4 26 20 PM" src="https://user-images.githubusercontent.com/87696933/202425433-210a83f8-4326-4b87-b0cf-40235cc9825e.png">

**Comment by juanbrits** [comment]
Hello @sagargg from what I can see this extension currently restricts access but you have to type in a username. 

The clients requirement is to restrict access by the user type, and specifically the end user? Below are some examples that I believe they'd like to filter:

- End-user
- Member
- Editor
- Sysadmin

**Comment by juanbrits** [comment]
@sagargg to investigate if this is a possibility - and what the estimation is?

**Comment by sagargg** [comment]
@juanbrits  it is possible but would take 1 or 2 days to implement.
cc @MuhammadIsmailShahzad

**Comment by juanbrits** [comment]
Okay thank you @sagargg . 
Please will you proceed with the implementation.

**Comment by juanbrits** [comment]
When we have access restriction = allowed users only we should be able to select multiple user types. 

For example if I want to restrict end users from seeing the resource, I will select editor, sysadmin, member. 
Through doing this only the selected user types will have access to the resource.

**Comment by sagargg** [comment]
@juanbrits  Don't think that is possible but we could add more options something similar to the screenshot. 
<img width="481" alt="Screenshot 2022-11-23 at 2 39 56 PM" src="https://user-images.githubusercontent.com/87696933/203505513-52110e07-5522-4045-b7b6-1117a308b46c.png">

**Comment by sagargg** [comment]
Also, I don't we sysadmin option because the sysadmin will have access to everything.

**Comment by juanbrits** [comment]
For now, we will keep implementation as is and see if this will work for the client's requirements. 
We will ask the client for more information in our kickoff meeting on the 24th of November 22.

**Comment by sagargg** [comment]
**DONE**
